### ISSUE TITLE
Proper use of 401/403 status codes

### ISSUE THREAD

**Issue by cnrdh** [npolar/gouncer#2]
401 Unauthorized
The 401 Unauthorized status indicates that the request had missing/invalid authentication credentials.
=> ie. login failed, token expired

403 Forbidden
The 403 Forbidden status indicates that although the request was valid the action requested failed authorization constraints. => ie. permission denied

From
http://blog.thefrontiergroup.com.au/2012/08/http-status-codes-and-restful-api-crafting/

**Comment by RDux** [comment]
Fixed in https://github.com/npolar/gouncer/commit/abdc480fe0b8c572ab7b5c7f66d596614b370f4a
